server:
  port: 9090

#spring:
#  application:
#    name: AUTH-SERVICE
#
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/s2taaa/cloudconfigserver
#          default-label: main
#        bootstrap: false

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://ec2-54-169-171-22.ap-southeast-1.compute.amazonaws.com:8761/eureka
      #defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost